// Code generated by "stringer -type=EtherType -output ether_string.go"; DO NOT EDIT.

package packet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EtherTypeTooLow-2047]
	_ = x[EthernetTypeIPv4-2048]
	_ = x[EthernetTypeARP-2054]
	_ = x[EthernetTypeIPv6-34525]
	_ = x[EtherTypeTooHigh-34526]
}

const (
	_EtherType_name_0 = "EtherTypeTooLowEthernetTypeIPv4"
	_EtherType_name_1 = "EthernetTypeARP"
	_EtherType_name_2 = "EthernetTypeIPv6EtherTypeTooHigh"
)

var (
	_EtherType_index_0 = [...]uint8{0, 15, 31}
	_EtherType_index_2 = [...]uint8{0, 16, 32}
)

func (i EtherType) String() string {
	switch {
	case 2047 <= i && i <= 2048:
		i -= 2047
		return _EtherType_name_0[_EtherType_index_0[i]:_EtherType_index_0[i+1]]
	case i == 2054:
		return _EtherType_name_1
	case 34525 <= i && i <= 34526:
		i -= 34525
		return _EtherType_name_2[_EtherType_index_2[i]:_EtherType_index_2[i+1]]
	default:
		return "EtherType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
